### ISSUE TITLE
Alpine linux failing to build with gcc 11.2.1

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2990]
https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-alpine-linux-x64-temurin/57/console
```
00:45:44  /home/adoptopenjdk/workspace/build-scripts/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin/workspace/build/src/src/hotspot/share/gc/shenandoah/shenandoahBarrierSet.inline.hpp:219:62: error: invalid cast from type 'std::nullptr_t' to type 'oopDesc**'
```
Was previously compiling fine with gcc 10.3.1

**Comment by sxa** [comment]
The [base dockerfile](https://github.com/adoptium/infrastructure/blob/master/ansible/docker/Dockerfile.Alpine3) we pull from to create the build image is alpine:3 so it's likely this has been caused by an update of that tag to point at 3.16 instead of 3.15 so picking up the later compiler version which is in that release (Looking at the SBOM we don't seem to capture the OS version in there)

We'll need to choose whether to get a fix upstream or lock it back to 3.15 for now.

**Comment by andrew-m-leonard** [comment]
I can raise a bug upstream, but for the mean time move back to 3.15 i'd suggest

**Comment by karianna** [comment]
CC @calderast and @gdams

**Comment by sxa** [comment]
@andrew-m-leonard Can you PR that into the dockerfile?

(Caveat: For some reason it doesn't look like it's regenerating the image from the dockerfile properly at the moment which is why it's not picking up the boot JDK properly...)

I've built a local image from the dockerfile with 3.16 and it's also failing on JDK8 - although I'm working on the assumption I don't need any magic options to build from the temurin mirrors:
```
/home/sxa/temurin-build/build-farm/workspace/build/src/hotspot/src/share/vm/adlc/dict2.cpp: In function 'int hashstr(const void*)':
/home/sxa/temurin-build/build-farm/workspace/build/src/hotspot/src/share/vm/adlc/dict2.cpp:286:17: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
  286 |   register char c, k = 0;
      |                 ^
```
JDK11 builds ok with GCC11.2.1

**Comment by andrew-m-leonard** [comment]
Raised: https://bugs.openjdk.org/browse/JDK-8288849

**Comment by andrew-m-leonard** [comment]
Fixed

**Comment by sxa** [comment]
To be clear the problem with failing to build with 11.2.1 has not been fixed as we have downgraded to an OS level which has a different default GCC. I wonder if we should start using our own fixed GCC levels for the build like we do for the main Linux builds? It would seem worth considering using GCC11 for JDK head for consistency.
