### ISSUE TITLE
jdk11u does not compile with the Adoptium GCC14.2 devkit

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#4294]
Noted while doing some build testing on my laptop which only has gcc installed via the Adoptium devkit for 14.2.0. I remember having this work in the past with the older devkit (11.3.0) and it still does for, but jdk11u will not build correctly with our GCC 14.2.0 devkit. jdk17u is ok with GCC14. Here is the failure:

```
Creating support/native/jdk.crypto.cryptoki/libj2pkcs11/static/libj2pkcs11.a from 14 file(s)
Creating support/native/jdk.management/libmanagement_ext/static/libmanagement_ext.a from 8 file(s)
In function 'mp_zero',
    inlined from 'mp_zero' at ../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:316:8,
    inlined from 'mp_set_int' at ../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:353:3,
    inlined from 'mp_cmp_int' at ../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:1735:26:
../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:321:3: error: 'tmp.alloc' may be used uninitialized [-Werror=maybe-uninitialized]
  321 |   s_mp_setz(DIGITS(mp), ALLOC(mp));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c: In function 'mp_cmp_int':
../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:1730:11: note: 'tmp' declared here
 1730 |   mp_int  tmp;
      |           ^~~
In function 'mp_zero',
    inlined from 'mp_zero' at ../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:316:8,
    inlined from 'mp_set_int' at ../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:353:3,
    inlined from 'mp_cmp_int' at ../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:1735:26:
../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:321:3: error: 'tmp.dp' may be used uninitialized [-Werror=maybe-uninitialized]
  321 |   s_mp_setz(DIGITS(mp), ALLOC(mp));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c: In function 'mp_cmp_int':
../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:1730:11: note: 'tmp' declared here
 1730 |   mp_int  tmp;
      |           ^~~
In function 'mp_zero',
    inlined from 'mp_zero' at ../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:316:8,
    inlined from 'mp_set_int' at ../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:353:3,
    inlined from 'mp_cmp_int' at ../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:1735:26:
../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:321:3: error: 'tmp.alloc' may be used uninitialized [-Werror=maybe-uninitialized]
  321 |   s_mp_setz(DIGITS(mp), ALLOC(mp));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c: In function 'mp_cmp_int':
../src/jdk.crypto.ec/share/native/libsunec/impl/mpi.c:1730:11: note: 'tmp' declared here
 1730 |   mp_int  tmp;
      |           ^~~
cc1: all warnings being treated as errors
gmake[3]: *** [Lib-jdk.crypto.ec.gmk:43: /home/sxa/buildtest/workspace/build/src/build/linux-x86_64-normal-server-release/support/native/jdk.crypto.ec/libsunec/static/mpi.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
gmake[2]: *** [make/Main.gmk:228: jdk.crypto.ec-static-libs] Error 2
gmake[2]: *** Waiting for unfinished jobs....
Note: Some input files use or override a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
Running nasgen
../src/java.base/unix/native/libjli/java_md_common.c: In function 'Resolve':
../src/java.base/unix/native/libjli/java_md_common.c:131:43: error: '%s' directive output may be truncated writing up to 4095 bytes into a region of size between 2 and 4097 [-Werror=format-truncation=]
  131 |     JLI_Snprintf(name, sizeof(name), "%s%c%s", indir, FILE_SEPARATOR, cmd);
      |                                           ^~
In file included from ../src/java.base/unix/native/libjli/java_md.h:36,
                 from ../src/java.base/share/native/libjli/java.h:41,
                 from ../src/java.base/unix/native/libjli/java_md_common.c:25:
../src/java.base/share/native/libjli/jli_util.h:103:41: note: 'snprintf' output between 2 and 8192 bytes into a destination of size 4098
  103 | #define JLI_Snprintf                    snprintf
../src/java.base/unix/native/libjli/java_md_common.c:131:5: note: in expansion of macro 'JLI_Snprintf'
  131 |     JLI_Snprintf(name, sizeof(name), "%s%c%s", indir, FILE_SEPARATOR, cmd);
      |     ^~~~~~~~~~~~
cc1: all warnings being treated as errors
gmake[3]: *** [CoreLibraries.gmk:242: /home/sxa/buildtest/workspace/build/src/build/linux-x86_64-normal-server-release/support/native/java.base/libjli/static/java_md_common.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
../src/java.base/share/native/libjli/java.c: In function 'TranslateApplicationArgs':
../src/java.base/share/native/libjli/java.c:1698:35: error: the comparison will always evaluate as 'false' for the pointer operand in 'arg + 2' must not be NULL [-Werror=address]
 1698 |             *nargv++ = ((arg + 2) == NULL) ? NULL : JLI_StringDup(arg + 2);
      |                                   ^~
cc1: all warnings being treated as errors
gmake[3]: *** [CoreLibraries.gmk:242: /home/sxa/buildtest/workspace/build/src/build/linux-x86_64-normal-server-release/support/native/java.base/libjli/static/java.o] Error 1
gmake[2]: *** [make/Main.gmk:228: java.base-static-libs] Error 2

```

Unclear how important this is. If we choose to move to using a devkit for versions pre-21 (to allow us to remove additional compilers from the build image) then we may choose to stick with the 11.3.0 one for 11 and 17, but I felt it was worth documenting it in case anyone else hits it.
