### ISSUE TITLE
AIX LTS builds 8 and 11 failing when built on AIX 7.2 machines.

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3261]
https://github.com/adoptium/ci-jenkins-pipelines/pull/622 is in to adjust the configurations to use AIX 7.2 for building AIX LTS releases, on the basis that AIX 7.1 is going out of support soon.

The build for JDK17 is running ok but as per one of the comments in there (repeasted below) it's currently failing for 8 and 11 and will need some remedial work:

- [JDK8](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-temurin/232/console): jdk/src/share/classes/jdk/internal/platform/Metrics.java:57: error: cannot find symbol on SystemMetrics
- [JDK11](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/192/console): Not quite sure where the underlying failure is

**Comment by sxa** [comment]
@backwaterred has confirmed to me that he has been able to successfully build JDK11 on one of his AIX 7.2 machines using the same XLC `16.0.10000.0011` compiler that's on ours.

**Comment by sxa** [comment]
@backwaterred confirmed that JDK8u doesn't build on AIX 7.2 for him either with some issues in `SystemMetrics.java`

**Comment by sxa** [comment]
Re-running JDK8 on AIX 7.2 with last GA tag at https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-temurin/234/

**Comment by backwaterred** [comment]
FYI, jdk8u should be building again after https://github.com/openjdk/jdk8u/pull/33 fixed the SystemMetrics issue.

**Comment by sxa** [comment]
New attempts:

- JDK8: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-temurin/268
- JDK11: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/214

**Comment by sxa** [comment]
8 passed: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/220/
11 failed but that's because there's a [third machine](https://ci.adoptium.net/computer/test-osuosl-aix72-ppc64-2) that needed the `OBJECT_MODE` option. Re-running at https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/221/

**Comment by adamfarley** [comment]
The only failures left here seem to be the 715 test issue which has [been fixed.](https://github.com/adoptium/ci-jenkins-pipelines/pull/622/files)

@sxa - Please close if you agree this is resolved.

**Comment by sxa** [comment]
Is like to ensure that we've successfully run a test on all 7.2 machines labelled as build before officially closing this. I thought we had at least one still offline but I could be wrong.

**Comment by sxa** [comment]
See https://github.com/adoptium/infrastructure/issues/3038 as an example

**Comment by aixtools** [comment]
See https://github.com/adoptium/infrastructure/issues/3052 and https://github.com/adoptium/infrastructure/issues/3053 re: machine definitions (ansible inventory).

Note: there is (currently) only one AIX 7.2 system labeled as `build`.

**Comment by sxa** [comment]
> Note: there is (currently) only one AIX 7.2 system labelled as build.

Yeah - that's down to https://github.com/adoptium/infrastructure/issues/3038, but I'm happy to close this since the original problem is likely with the specific machines in that issue now and not a general issue with all AIX 7.2 systems based on the fact we completed the April releases on AIX 7.2

**Comment by adamfarley** [comment]
FYI: As mentioned [here](https://github.com/adoptium/temurin-build/issues/3389#issuecomment-1587266403), a [jdk8 build of aix](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-temurin/303/) on build-osuosl-aix72-ppc64-2 was recently found to have failed with this error:

```
13:05:57  BOOT JDK: /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-temurin/build-farm/platform-specific-configurations/aix.sh: line 109: /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-temurin/jdk-7/bin/java: A file or directory in the path name does not exist.
```

This appears to have been caused by an incorrect boot jdk location for building jdk8 in the machine's jenkins environment variables. A JDK8 was found to be present in a different folder (as per the variable setting for another aix machine), so the variable was modified on Jenkins and the build was re-run [here](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-temurin/304/).

This appears to have solved the problem. Noting here for posterity.

**Comment by sxa** [comment]
> FYI: As mentioned https://github.com/adoptium/temurin-build/issues/3389#issuecomment-1587266403, a [JDK8 build of aix](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-temurin/303/) on build-osuosl-aix72-ppc64-2 was recently found to have failed

Noting that this occurred on the new machine added in https://github.com/adoptium/infrastructure/pull/3069

**Comment by sxa** [comment]
It's not quite a new machine - it was cloned from another one. Do you have the info on what the path was and what you updated it it? I suspect we cloned the new AIX box from one machine but the jenkins definition got copied from a different one that was slightly different.

**Comment by adamfarley** [comment]
I think the path began "/home/jenkins" and ended with "jdk-7". At one point, I thought [this](https://github.com/adoptium/infrastructure/blob/348b26cbc5914a1936e8b2cac89df822923e029f/ansible/pbTestScripts/buildJDK.sh#L82) could be to blame, though I'm unclear as to how it went wrong.

**Comment by adamfarley** [comment]
Ok, now we're having the same problem on [test-osuosl-aix72-ppc64-6](https://ci.adoptium.net/computer/test-osuosl-aix72-ppc64-6).

```
/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-temurin/build-farm/platform-specific-configurations/aix.sh: line 109: /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-temurin/jdk-7/bin/java: A file or directory in the path name does not exist.
```

Can someone with Jenkins admin access please review the JDK7 boot JDK setting and see if there's a java 8 build in /usr/java8_64 that can be used to replace the current value?

Also, please check test-osuosl-aix72-ppc64-5 as well. I'd like to get out ahead of this.

**Comment by steelhead31** [comment]
@adamfarley I've updated this on test-osuosl-aix72-ppc64-5 & test-osuosl-aix72-ppc64-6

**Comment by adamfarley** [comment]
Thanks!

**Comment by sxa** [comment]
Noting that using `/usr/j2sdk-image` as a JDK7 boot JDK works correctly.
I've removed the `build` and `build72` labels from all of the test machines as we now have two dedicated build systems so we should not be building on the test systems.
