### ISSUE TITLE
Test build JDK8 on GCC11

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3758]
Should be possible with the patch from https://github.com/openjdk/jdk8u-dev/pull/357#issuecomment-2048858831

**Comment by sxa** [comment]
Running with `--with-devkit` [didn't work](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-temurin/447/console) via jenkins as it objected to not being able to find freetype:
`configure: error: Could not find freetype! You might be able to fix this by running 'sudo yum install freetype-devel'.`

Building a hotspot variant from the command line on aarch64 with CC and CXX set to the versions in /usr/local/gcc11/bin on the CentOS7 container also didn't work.

Same build with gcc-7.5 hit issues too though, so more investigation required to build from the branch.

**Comment by sxa** [comment]
Scratch the previous comment. Building with 11.2 doesn't work but 10.3 is ok.
11.2 gives a series of C++17 violation errors:
```
/home/sxa/temurin-build/build-farm/workspace/build/src/hotspot/src/share/vm/adlc/arena.cpp: In member function 'size_t Arena::used() const':
/home/sxa/temurin-build/build-farm/workspace/build/src/hotspot/src/share/vm/adlc/arena.cpp:82:19: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
   82 |   register Chunk *k = _first;
      |                   ^
```

**Comment by sxa** [comment]
OK GCC 10.3 works ok, 11.2 does not. I've tried with an 11.3 build and that has the same issues as 11.2:
`/home/sxa/temurin-build/build-farm/workspace/build/src/hotspot/src/share/vm/opto/type.cpp:2556:71: error: 'this' pointer is null [-Werror=nonnull]`

**Comment by sxa** [comment]
With GCC13.2 I get this:
`/home/sxa/temurin-build/build-farm/workspace/build/src/hotspot/src/os_cpu/linux_aarch64/vm/orderAccess_linux_aarch64.inline.hpp:78:28: error: 'long unsigned int __atomic_load_8(const volatile void*, int)' writing 8 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]`

**Comment by sxa** [comment]
Revisiting now that the PR in the original comment has been merged into jdk8u-dev.
Using the devkit still has an issue with freetype as per the [earlier comment](https://github.com/adoptium/temurin-build/issues/3758#issuecomment-2075138363) but using our self-built gcc 11.2 looks better but still doesn't run to completion:

https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-temurin/468/console
```
12:09:09  Tools summary:
12:09:09  * Boot JDK:       java version "1.7.0_261" OpenJDK Runtime Environment (rhel-2.6.22.2.el7_8-aarch64 u261-b02) OpenJDK 64-Bit Server VM (build 24.261-b02, mixed mode)  (at /usr/lib/jvm/java-1.7.0-openjdk)
12:09:09  * Toolchain:      gcc (GNU Compiler Collection)
12:09:09  * C Compiler:     Version 11.2.0 (at /usr/local/gcc11/bin/gcc-11.2)
12:09:09  * C++ Compiler:   Version 11.2.0 (at /usr/local/gcc11/bin/g++-11.2)
```
```
12:12:58      inlined from 'static const TypeAryPtr* TypeAryPtr::make(TypePtr::PTR, const TypeAry*, ciKlass*, bool, int, int, const TypeOopPtr*, int)' at /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/opto/type.cpp:3745:115:
12:12:58  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/opto/type.cpp:2556:71: error: 'this' pointer is null [-Werror=nonnull]
12:12:58   2556 |           ciInstanceKlass* k = o->as_instance()->java_lang_Class_klass()->as_instance_klass();
12:12:58        |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
12:12:58  In file included from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciCallSite.hpp:28,
12:12:58                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/code/dependencies.hpp:28,
12:12:58                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciEnv.hpp:32,
12:12:58                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciUtilities.hpp:28,
12:12:58                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciNullObject.hpp:30,
12:12:58                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciConstant.hpp:29,
12:12:58                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciArray.hpp:29,
12:12:58                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/precompiled/precompiled.hpp:33:
12:12:58  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciInstance.hpp: In function 'static const TypeAryPtr* TypeAryPtr::make(TypePtr::PTR, const TypeAry*, ciKlass*, bool, int, int, const TypeOopPtr*, int)':
12:12:58  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciInstance.hpp:68:12: note: in a call to non-static member function 'ciKlass* ciInstance::java_lang_Class_klass()'
12:12:58     68 |   ciKlass* java_lang_Class_klass();
12:12:58        |            ^~~~~~~~~~~~~~~~~~~~~
12:12:58  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/cpu/aarch64/vm/vm_version_aarch64.cpp
12:12:58  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/cpu/aarch64/vm/vm_version_ext_aarch64.cpp
12:12:58  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/os_cpu/linux_aarch64/vm/vm_version_linux_aarch64.cpp
12:12:58  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/code/vmreg.cpp
12:12:58  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/cpu/aarch64/vm/vmreg_aarch64.cpp
12:12:59  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/code/vtableStubs.cpp
12:12:59  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/cpu/aarch64/vm/vtableStubs_aarch64.cpp
12:12:59  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/prims/whitebox.cpp
12:12:59  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/prims/whitebox_ext.cpp
12:12:59  In constructor 'TypeOopPtr::TypeOopPtr(Type::TYPES, TypePtr::PTR, ciKlass*, bool, ciObject*, int, int, const TypeOopPtr*, int)',
12:12:59      inlined from 'static const TypeOopPtr* TypeOopPtr::make(TypePtr::PTR, int, int, const TypeOopPtr*, int)' at /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/opto/type.cpp:2591:108:
12:12:59  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/opto/type.cpp:2556:71: error: 'this' pointer is null [-Werror=nonnull]
12:12:59   2556 |           ciInstanceKlass* k = o->as_instance()->java_lang_Class_klass()->as_instance_klass();
12:12:59        |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
12:12:59  In file included from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciCallSite.hpp:28,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/code/dependencies.hpp:28,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciEnv.hpp:32,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciUtilities.hpp:28,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciNullObject.hpp:30,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciConstant.hpp:29,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciArray.hpp:29,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/precompiled/precompiled.hpp:33:
12:12:59  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciInstance.hpp: In static member function 'static const TypeOopPtr* TypeOopPtr::make(TypePtr::PTR, int, int, const TypeOopPtr*, int)':
12:12:59  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciInstance.hpp:68:12: note: in a call to non-static member function 'ciKlass* ciInstance::java_lang_Class_klass()'
12:12:59     68 |   ciKlass* java_lang_Class_klass();
12:12:59        |            ^~~~~~~~~~~~~~~~~~~~~
12:12:59  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/utilities/workgroup.cpp
12:12:59  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/utilities/xmlstream.cpp
12:12:59  In constructor 'TypeOopPtr::TypeOopPtr(Type::TYPES, TypePtr::PTR, ciKlass*, bool, ciObject*, int, int, const TypeOopPtr*, int)',
12:12:59      inlined from 'TypeAryPtr::TypeAryPtr(TypePtr::PTR, ciObject*, const TypeAry*, ciKlass*, bool, int, int, bool, const TypeOopPtr*, int)' at /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/opto/type.hpp:1094:39,
12:12:59      inlined from 'static const TypeAryPtr* TypeAryPtr::make(TypePtr::PTR, const TypeAry*, ciKlass*, bool, int, int, const TypeOopPtr*, int)' at /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/opto/type.cpp:3745:115:
12:12:59  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/opto/type.cpp:2556:71: error: 'this' pointer is null [-Werror=nonnull]
12:12:59   2556 |           ciInstanceKlass* k = o->as_instance()->java_lang_Class_klass()->as_instance_klass();
12:12:59        |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
12:12:59  In file included from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciCallSite.hpp:28,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/code/dependencies.hpp:28,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciEnv.hpp:32,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciUtilities.hpp:28,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciNullObject.hpp:30,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciConstant.hpp:29,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciArray.hpp:29,
12:12:59                   from /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/precompiled/precompiled.hpp:33:
12:12:59  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciInstance.hpp: In static member function 'static const TypeAryPtr* TypeAryPtr::make(TypePtr::PTR, const TypeAry*, ciKlass*, bool, int, int, const TypeOopPtr*, int)':
12:12:59  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/ci/ciInstance.hpp:68:12: note: in a call to non-static member function 'ciKlass* ciInstance::java_lang_Class_klass()'
12:12:59     68 |   ciKlass* java_lang_Class_klass();
12:12:59        |            ^~~~~~~~~~~~~~~~~~~~~
12:12:59  Compiling /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/src/share/vm/utilities/yieldingWorkgroup.cpp
12:12:59  Making signal interposition lib...
12:12:59  cc1: warning: command-line option '-std=gnu++98' is valid for C++/ObjC++ but not for C
12:12:59  Making SA debugger back-end...
12:12:59  cc1: warning: command-line option '-std=gnu++98' is valid for C++/ObjC++ but not for C
12:13:00  cc1: warning: command-line option '-std=gnu++98' is valid for C++/ObjC++ but not for C
12:13:00  cc1: warning: command-line option '-std=gnu++98' is valid for C++/ObjC++ but not for C
12:13:01  cc1plus: all warnings being treated as errors
12:13:01  cc1: warning: command-line option '-std=gnu++98' is valid for C++/ObjC++ but not for C
12:13:01  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/make/linux/makefiles/rules.make:149: recipe for target 'type.o' failed
12:13:01  gmake[6]: *** [type.o] Error 1
12:13:01  gmake[6]: *** Waiting for unfinished jobs....
12:13:02  cc1: warning: command-line option '-std=gnu++98' is valid for C++/ObjC++ but not for C
12:13:02  cc1: warning: command-line option '-std=gnu++98' is valid for C++/ObjC++ but not for C
12:13:02  cc1: warning: command-line option '-std=gnu++98' is valid for C++/ObjC++ but not for C
12:13:04  gmake[5]: *** [the_vm] Error 2
12:13:04  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/make/linux/makefiles/top.make:119: recipe for target 'the_vm' failed
12:13:04  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/hotspot/make/linux/Makefile:284: recipe for target 'product' failed
12:13:04  gmake[4]: *** [product] Error 2
12:13:04  Makefile:230: recipe for target 'generic_build2' failed
12:13:04  gmake[3]: *** [generic_build2] Error 2
12:13:04  Makefile:177: recipe for target 'product' failed
12:13:04  gmake[2]: *** [product] Error 2
12:13:04  HotspotWrapper.gmk:44: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/build/linux-aarch64-normal-server-release/hotspot/_hotspot.timestamp' failed
12:13:04  gmake[1]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/build/linux-aarch64-normal-server-release/hotspot/_hotspot.timestamp] Error 2
12:13:04  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src//make/Main.gmk:109: recipe for target 'hotspot-only' failed
12:13:04  make: *** [hotspot-only] Error 2
12:13:04  OpenJDK make failed, archiving make failed logs
12:13:04  Copying build.log to TemurinLogsArchive
12:13:04  Archiving and compressing with pigz
12:13:04  
12:13:04  real	0m0.015s
12:13:04  user	0m0.011s
12:13:04  sys	0m0.009s
12:13:04  Your archive was created as /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/build/src/build/linux-aarch64-normal-server-release/OpenJDK.tar.gz
12:13:04  Moving the artifact to location /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-temurin/workspace/target//OpenJDK8U-makefailurelogs_aarch64_linux_hotspot_2024-08-16-11-05.tar.gz
12:13:04  archive done.
12:13:04  Failed to make the JDK, exiting
```
Memo to self: The above run was with:
- `VARIANT: "hotspot"`
- `-r https://github.com/openjdk/jdk8u-dev --disable-adopt-branch-safety -b master` added to `BUILD_ARGS`
- `"USE_ADOPT_SHELL_SCRIPTS": false,`
- And in DEFAULTS_JSON using my [gcc11 branch](https://github.com/sxa/temurin-build/commits/gcc11_everywhere/) of temurin-build:
```
    "repository": {
        "build_branch": "gcc11_everywhere",
        "build_url": "https://github.com/sxa/temurin-build.git",
```
- `"ENABLE_TESTS": false"` (but that's not significant)
